FROM ubuntu:22.04 as builder

WORKDIR /neovim
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install ninja-build gettext cmake unzip curl build-essential fuse libfuse-dev file
RUN make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/dist/nvim-linux64"
RUN make install
